config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/secret'
  
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "welcome#index"
  resources :events
 resources :users
  resources :welcome, only: [:index, :show]
  
  # Defines the root path route ("/")
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :image
  belongs_to :admin, class_name: "User"
  has_many :attendances
  has_many :users, through: :attendencies
  
  validates :start_date, presence: true, :comparison => { :greater_than => Time.current}
  validates :duration, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
  validate :divisible_by_five
  
  validates :title, presence: true, length: { in: 5..140 }
  validates :description, presence: true, length: { in: 20..1000}
  validates :price, presence: true
  validates_inclusion_of :price, :in => 1..1000
  validates :location, presence: true

  def divisible_by_five
    if (self.duration % 5) != 0
      self.errors[:base] << "Number must be divisible by 5!"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :avatar
  extend Devise::Models
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         after_create :welcome_send

    
    has_many :events, class_name: "Event"
    has_many :attendances
    has_many :events, through: :attendencies

    def welcome_send
        UserMailer.welcome_email(self).deliver_now
      end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
      
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # before_action :authenticate_user!
  # before_action :set_event, execpt: [:show]
  # before_action :check_admin, only: [:edit, :update, :destroy]
  # skip_before_action :require_login, only: [:new, :create]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.admin_id = current_user.id
    if @event.save(validate: false)
      redirect_to @event
    else
      render :new
    end
    
  end

  def edit
    @event = Event.find(params[:id])

  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
  
    redirect_to welcome_index_path
  end
end

private

def event_params
  params.require(:event).permit(:start_date, :duration,:title, :description, :price, :location, :image)
end

def set_event
  @event = Event.find(params[:id])
end

def check_admin
  unless current_user && current_user.id == @event.admin_id
    redirect_to event_path, alert: "You don't have permission to do that."
  end

  
def authorize_user
  unless current_user == @event.admin_id
    redirect_to event_path, alert: "You are not authorized to perform this action."
  end
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.create(user_params).save(validate: false)
    redirect_to welcome_index_path
  end
  def edit
    @user = User.find(params[:id])

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path
    else
      render 'edit'
    end
  end
end
private

def user_params
  params.require(:user).permit(:email, :description, :password, :first_name, :last_name, :avatar)
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    
  end

  def secret
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/edit.html.erb
<div class="container" style="width: 600px;">

<h1> Créer un évenement</h1>

<%= form_for @event do |f| %>
<div class="form-group">
<label> Nom de l'évenement </label> 
   <%= f.text_field :title, class: 'form-control' %>
   
   </div>
   <div class="form-group">
   <label> date de début </label> 
   <%= f.datetime_field :start_date, class: 'form-control' %>
   </div>
   <div class="form-group">
   <label> description </label> 
   <%= f.text_area :description, class: 'form-control' %>
   </div>
   <div class="form-group">
   <label> durée </label> 
   <%= f.number_field :duration, class: 'form-control' %>
   </div>
   <div class="form-group">
   <label> lieux </label> 
   <%= f.text_area :location, class: 'form-control' %>
   </div>
   <div class="form-group">
   <label> price </label> 
   <%= f.number_field :price, class: 'form-control' %>
   </div>
   <div class="form-group">
   <label> Ajouter une image a l'evenement </label> 
   <%= f.file_field :image, class: "form-control" %>
   </div>
   <div class="form-group">
   <button type="submit" class="btn btn-success">Modifier l'événement</button>
   </div>
<% end %>

<a href="<%= welcome_index_path %>" class="btn btn-primary">revenir a la page d'acceuil</a>
<%= link_to "revenir a la page de l'évenement", event_path(@event.id), class: "btn btn-success my-2" %>
</div>

app/views/events/new.html.erb
<div class="container" style="width: 600px;">

<h1> Créer un évenement</h1>

<%= form_for @event do |f| %>
<div class="form-group">
<label> Nom de l'évenement </label> 
   <%= f.text_field :title, class: 'form-control' %>
   
   </div>
   <div class="form-group">
   <label> date de début </label> 
   <%= f.datetime_field :start_date, class: 'form-control' %>
   </div>
   <div class="form-group">
   <label> description </label> 
   <%= f.text_area :description, class: 'form-control' %>
   </div>
   <div class="form-group">
   <label> durée </label> 
   <%= f.number_field :duration, class: 'form-control' %>
   </div>
   <div class="form-group">
   <label> lieux </label> 
   <%= f.text_area :location, class: 'form-control' %>
   </div>
   <div class="form-group">
   <label> price </label> 
   <%= f.number_field :price, class: 'form-control' %>
   </div>
   <div class="form-group">
   <label> Ajouter une image a l'evenement </label> 
   <%= f.file_field :image, class: "form-control" %>
   </div>
   <div class="form-group">
   <button type="submit" class="btn btn-success">Créer l'événement</button>
   </div>
<% end %>

<a href="<%= welcome_index_path %>" class="btn btn-primary">revenir a la page d'acceuil</a>

</div>

app/views/events/show.html.erb
    <div class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading"><%= @event.title %></h1><br/>
          <p class="lead text-muted"><%= @event.description %></p>
          <% if @event.image.attached? %>
              <%= image_tag(@event.image, style: 'width:500px; height:800;') %>
          <% end %>


          <p>
            <% if current_user && current_user.id == @event.admin_id %>
                <%= link_to "Modifier", edit_event_path(@event.id), class: "btn btn-secondary my-2"   %>
                <%= link_to "Suprimer", event_path(@event.id),class: "btn btn-danger my-2", method: :delete, data: { turbo_method: :delete, turbo_confirm: "Êtes-vous sûr de vouloir supprimer cet élément ?" } %><br/>
                <%= link_to "revenir a la page d'acceuil", welcome_index_path(@event.id), class: "btn btn-primary my-2" %>
                    <br/>
            <% else %>
                <%= link_to "revenir a la page d'acceuil", welcome_index_path(@event.id), class: "btn btn-primary my-2" %>
            <% end %>
          </p>
        </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EvnetbriteLike</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
 <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/jumbotron/">

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="jumbotron.css" rel="stylesheet">
 
 </head>

  <body>
  
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark";>
  
      <a class="navbar-brand" href="#">EvnetbriteLike</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "home", welcome_index_path, class: "nav-link" %>
            
          </li>
          </li>
        </ul>
        <ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path,class: "btn btn-danger my-2", 'data-turbo-method': :delete %>
  <%= link_to "Profil", user_path(current_user.id), class: "btn btn-warning my-2" %>

    </li>
  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path, class: "btn btn-success my-2" %>
      <%= link_to "Sign up", new_user_registration_path , class: "btn btn-primary my-2"%>
    </li>

  <% end %>
</ul>
        <%# <p><%= link_to "connexion", new_user_session_path, class: "btn btn-success my-2" %>
         <%# <p><%= link_to "inscription", new_user_registration_path, class: "btn btn-primary my-2" %> %> %>
</div>
    </nav>
    <div style="padding-top: 7rem;">
      <%= yield %>
  </div>
   
   <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  
  </body>
</html>

app/views/users/edit.html.erb
<div class="container" style="width: 600px;">

<h1> Modifier les informations du profil</h1>

<%= form_for @user do |f| %>
<div class="form-group">

   <div class="form-group">
   <label> first_name </label> 
   <%= f.text_field :first_name, class: 'form-control' %>
   </div>
   <div class="form-group">
   <label> last_name </label> 
   <%= f.text_field :last_name, class: 'form-control' %>
   </div>
   <label> description </label> 
   <%= f.text_field :description, class: 'form-control' %>
   </div>
   <div class="form-group">
   <label> Ajouter ou modifier l'avatar </label> 
   <%= f.file_field :avatar, class: "form-control" %>
   </div>
   <div class="form-group">
   <button type="submit" class="btn btn-success">Update</button>
   </div>
<% end %>


<%= link_to "Back", user_path(@user.id), class: "btn btn-success my-2" %>
</div>

app/views/users/show.html.erb
<section style="background-color: #eee;">
  <div class="container py-5">
    <div class="row">
      <div class="col">
        <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
          <ol class="breadcrumb mb-0">
            <%= link_to "Home", welcome_index_path, class: "breadcrumb-item" %>
            <%= link_to "User", welcome_index_path(@user.id), class: "breadcrumb-item" %>
            <li class="breadcrumb-item active" aria-current="page">User Profile</li>
          </ol>
        </nav>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
            <% if @user.avatar.attached? %>
              <%= image_tag(@user.avatar, class: "rounded-circle img-fluid", style: "width: 150px;") %>
              <% else %>
                <%= image_tag("https://gravatar.com/avatar/ea28cbf007dd2f1767a3dbab3a9d9363?s=400&d=robohash&r=x", class: "rounded-circle img-fluid", style: "width: 150px;") %>
          <% end %>
              
            <h5 class="my-3"><%= @user.first_name %></h5>
            
            <p class="text-muted mb-4"><%= @user.description %></p>
            <div class="d-flex justify-content-center mb-2">

              <%= link_to "Edit password/email",  edit_user_registration_path, class: "btn btn-primary"   %>
              <%= link_to "Edit User informations",  edit_user_path, class: "btn btn-outline-primary ms-1"%>
   
            </div>
          </div>
        </div>
        <div class="card mb-4 mb-lg-0">
          <div class="card-body p-0">
            
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">First Name</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.first_name %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Last_name</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.last_name %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Email</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @user.email %></p>
              </div>
            </div>
            <hr>
            </div>
          </div>
        </div>
        
    </div>
  </div>
</section>

app/views/welcome/index.html.erb
<div class="jumbotron">
        <div class="container">
          <h1 class="display-3">EventbriteLike!</h1>
          <p>notre site vous permet de crerr vos evenement facilement, vous aurez acces a une multitude de fonctionalité pour editer et proumouvoir votre evenement.</p>
          <% if signed_in? %>
          <p><%= link_to "créer un évenement", new_event_path, class: "btn btn-success my-2" %>
          <% end %>
        </div>
      </div>
      <div class="container" style="width: 1500px;">
<% @events.each do |event| %>
      
        <!-- Example row of columns -->
        <div class="row">
          <div class="col-xl-4">
            <h2><%= event.title %></h2>
            <p><%= event.description %></p>
           <p><%= link_to "voir l'évenement", event_path(event), class: "btn btn-secondary my-2" %>
          </div>
          </div>
<% end %>

app/views/welcome/secret.html.erb
<h1>Welcome#secret</h1>
<p>Find me in app/views/welcome/secret.html.erb</p>